fix: removing set +e in actions workflow so that it does not ignore errors

diff --git a/.github/workflows/action-terraform-verify.yml b/.github/workflows/action-terraform-verify.yml
--- a/.github/workflows/action-terraform-verify.yml
+++ b/.github/workflows/action-terraform-verify.yml
@@ -30,20 +30,16 @@ jobs:
           terraform_version: 1.2.4
       - name: Validate terraform fmt (added_modified)
         run: |
-          set +e
-
-          echo "CHECK_STATUS=0" >> $GITHUB_ENV
+          echo "CHECK_STATUS=0" >> $GITHUB_ENV  # Initialize CHECK_STATUS
 
           for changed_file in ${{ steps.pr_files.outputs.added_modified }}; do
             echo "Checking terraform fmt on ${changed_file}..."
 
             if [[ $changed_file == *.tf ]]; then
               terraform fmt -check $changed_file
-              FMT_STATUS=$(echo $?)
-
-              if [[ $FMT_STATUS -ne 0 ]]; then
+              if [[ $? -ne 0 ]]; then  # Check if terraform fmt failed
                 echo "❌ terraform fmt failed - ${changed_file}" >> $GITHUB_STEP_SUMMARY
-                echo "CHECK_STATUS=1" >> $GITHUB_ENV
+                echo "CHECK_STATUS=1" >> $GITHUB_ENV  # Set failure status
               fi
             fi
           done
